# Generated by Django 4.2.5 on 2024-05-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(default='no contact', max_length=15),
        ),
    ]
