# Generated by Django 4.2.5 on 2024-06-07 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_isapproved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='type',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='information',
            name='farmer',
        ),
        migrations.AddField(
            model_name='information',
            name='viewers',
            field=models.ManyToManyField(related_name='viewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agriculturalorganization',
            name='Licence',
            field=models.FileField(blank=True, null=True, upload_to='static/uploads/licences'),
        ),
        migrations.AlterField(
            model_name='information',
            name='tutorial',
            field=models.FileField(null=True, upload_to='static/uploads/tutorials'),
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agriculturalorganization')),
            ],
        ),
    ]
