# Generated by Django 4.2.5 on 2024-06-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_type_information_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agriculturalorganization',
            name='Licence',
        ),
        migrations.RemoveField(
            model_name='agriculturalorganization',
            name='communicationOfficer',
        ),
        migrations.RemoveField(
            model_name='agriculturalorganization',
            name='contact',
        ),
        migrations.AddField(
            model_name='agriculturalorganization',
            name='email',
            field=models.EmailField(default='none', max_length=254, unique=True),
        ),
    ]
