# Generated by Django 4.2.5 on 2024-06-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_agriculturalorganization_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculturalorganization',
            name='email',
            field=models.EmailField(default='ofwonodani12@gmail.com', max_length=254, unique=True),
        ),
    ]
