# Generated by Django 4.2.5 on 2024-06-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_agriculturalorganization_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculturalorganization',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
