# Generated by Django 4.2.5 on 2024-06-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_otp_otp_otp_code_otp_is_valid_otp_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='otp',
            old_name='created_at',
            new_name='created',
        ),
    ]
