# Generated by Django 5.0.6 on 2024-07-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pest',
            name='common_damage',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pest',
            name='preferred_habitat',
            field=models.TextField(),
        ),
    ]
