# Generated by Django 5.0.6 on 2024-07-10 21:35

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_comment_options_alter_notification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=50, scale=0.5, size=[500, 300], upload_to='static/uploads/photos'),
        ),
    ]
