# Generated by Django 5.0.6 on 2024-07-11 07:58

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=50, scale=None, size=[1920, 1080], upload_to='static/uploads/equipments'),
        ),
        migrations.AlterField(
            model_name='pest',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=50, scale=None, size=[1920, 1080], upload_to='static/uploads/pests'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=50, scale=None, size=[1920, 1080], upload_to='static/uploads/posts'),
        ),
    ]
